domain: seati.cc
bind-port: 9090
version: 0.10
enable-origin-whitelist: true
allowed-origins:
  - https://seati.cc
  - https://lab.seati.cc
database:
  host: localhost
  port: 3306
  user: ~
  password: ~
  dbname: ~
token:
  expiration: 1440 # 单位：分钟
  private-key: ~
need-authorize-handlers:
  - ExampleHandler